### ISSUE TITLE
Problem following biorbd 1.11.0 ?

### ISSUE THREAD

**Issue by EveCharbie** [pyomeca/bioviz#97]
Traceback (most recent call last):
  File "/home/charbie/Documents/Programmation/BiorbdOptim/bioptim/examples/getting_started/pendulum.py", line 208, in <module>
    main()
  File "/home/charbie/Documents/Programmation/BiorbdOptim/bioptim/examples/getting_started/pendulum.py", line 157, in main
    sol.animate(n_frames=100)
  File "/home/charbie/Documents/Programmation/BiorbdOptim/bioptim/optimization/solution/solution.py", line 1275, in animate
    self.ocp.nlp[i].model.animate(
  File "/home/charbie/Documents/Programmation/BiorbdOptim/bioptim/models/biorbd/biorbd_model.py", line 756, in animate
    all_bioviz.append(bioviz.Viz(biorbd_model.path, **kwargs))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/charbie/miniconda3/envs/dev_bioptim/lib/python3.11/site-packages/bioviz/__init__.py", line 255, in __init__
    for i, rt in enumerate(self.allGlobalJCS.get_data(Q=self.Q, compute_kin=False)):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/charbie/miniconda3/envs/dev_bioptim/lib/python3.11/site-packages/bioviz/interfaces_collection.py", line 37, in get_data
    self.get_data_func(**kwargs)
  File "/home/charbie/miniconda3/envs/dev_bioptim/lib/python3.11/site-packages/bioviz/interfaces_collection.py", line 287, in _get_data_from_eigen
    allJCS = self.m.allGlobalJCS()
             ^^^^^^^^^^^^^^^^^^^^^
TypeError: Joints.allGlobalJCS() missing 1 required positional argument: 'Q'

**Comment by pariterre** [comment]
Fixed in #98
